#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Language {
    English,
    German,
    Italian,
    Spanish,
    SpanishMexico,
    French,
    Polish,
    PortugueseBrazil,
    Chinese,
    Russian,
    Japanese,
    Czech,
    Hungarian,
    Danish,
    Finnish,
    Greek,
    Norwegian,
    Swedish,
    Turkish,
    Arabic,
    Korean,
    Thai,
    ChineseSimplified,
}

impl Language {
    pub const ALL: [Self; 23] = [
        Self::English,
        Self::German,
        Self::Italian,
        Self::Spanish,
        Self::SpanishMexico,
        Self::French,
        Self::Polish,
        Self::PortugueseBrazil,
        Self::Chinese,
        Self::Russian,
        Self::Japanese,
        Self::Czech,
        Self::Hungarian,
        Self::Danish,
        Self::Finnish,
        Self::Greek,
        Self::Norwegian,
        Self::Swedish,
        Self::Turkish,
        Self::Arabic,
        Self::Korean,
        Self::Thai,
        Self::ChineseSimplified,
    ];

    pub fn full_name(self) -> &'static str {
        match self {
            Self::English => "English",
            Self::German => "German",
            Self::Italian => "Italian",
            Self::Spanish => "Spanish",
            Self::SpanishMexico => "Spanish_Mexico",
            Self::French => "French",
            Self::Polish => "Polish",
            Self::PortugueseBrazil => "Portuguese_Brazil",
            Self::Chinese => "Chinese",
            Self::Russian => "Russian",
            Self::Japanese => "Japanese",
            Self::Czech => "Czech",
            Self::Hungarian => "Hungarian",
            Self::Danish => "Danish",
            Self::Finnish => "Finnish",
            Self::Greek => "Greek",
            Self::Norwegian => "Norwegian",
            Self::Swedish => "Swedish",
            Self::Turkish => "Turkish",
            Self::Arabic => "Arabic",
            Self::Korean => "Korean",
            Self::Thai => "Thai",
            Self::ChineseSimplified => "ChineseSimplified",
        }
    }
}
